<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Flixn Media Platform :: Forgot Password</title>
  <!--<link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/2.5.1/build/reset-fonts-grids/reset-fonts-grids.css" />-->
  <link rel="stylesheet" type="text/css" href="/css/index.css" />
  <link rel="stylesheet" type="text/css" href="/css/form.css" />
  <script type="text/javascript" src="/js/jquery-1.2.6.js"></script>
  <script type="text/javascript" src="/js/jquery.dump.js"></script>
  <script type="text/javascript" src="/js/jquery.form.js"></script>
  <script type="text/javascript" src="/js/ui/ui.core.js"></script>
  <script type="text/javascript" src="/js/ui/ui.dialog.js"></script>
  <script type="text/javascript" src="/js/ui/ui.draggable.js"></script>
  <script type="text/javascript" src="/js/ui/ui.resizable.js"></script>
  
    <script type="text/javascript">
    function clearDefault(el) {if (el.value=="USERNAME" || "EMAIL") el.value = ""}
    $(document).ready(function()
                      {if($("#status").html() == "&nbsp;")
                       {$("#status").css({visibility: "hidden"})}
                      
    
    $(".window").dialog({
                id: $(this).attr('id'),
    
                width: 460,
                height: 240,
                modal: false,
                overlay: {backgroundColor: "#000", opacity: ".8"},
                resizable: 'sw',

                dialogClass: 'fx',
                });
    });
    </script>
 </head>
 <body>
  <div class="window" title="FORGOT PASSWORD" id="forgot_window">
   <div id="content" title="">

    <form action="/<?= $this->Controller ?>/forgot" method="post" id="auth" title="">
     
     <div class="login">
     <input id="user" class="empty" type="text" name="username" value="USERNAME" onfocus="clearDefault(this)" title="" /><br />
     <input id="pass" class="empty" type="text" name="email" value="EMAIL" onfocus="clearDefault(this)" title="" /><br />
     <div id="status">&nbsp;<?= $this->status; ?></div>
     <input id="login_submit" type="submit" class="submit" value="" title="Submit" /><br />
     <div style="clear: both">
      <span id="forgot">
        <a href="/auth/forgot/" title="Forgot Password">Forgot Password?</a>
      </span>
      </div>
     </div>
     </form>
   </div>
  </div>
 </body>
</html>