<div class="window pre" id="component_preview" title="Preview" autoopen="true" wwidth="<?= $this->componentWidth ?>" wheight="<?= $this->componentHeight ?>" vposition="bottom" hposition="right">
    <div>
        <div style="background-color: #e0e6f2; border: 1px solid #a0a9b9; overflow: auto;">
            <div id="preview_con" style="style="width: <?= $this->componentWidth ?>px; height: <?= $this->componentHeight ?>px;">
            <div id="component_preview_container" style="width: <?= $this->componentWidth ?>px; height: <?= $this->componentHeight ?>px;">
                <div id="component_preview" style="margin:0;padding:0;">
                    <a href="http://www.macromedia.com/go/getflashplayer">Get the Flash Player</a> to see this player.
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
$(document).ready(function(){

var waitFlag = true;
var p = window.setTimeout("noOverlap()", 10);

});
</script>
